In [1]:
print("hello world")

hello world


In [4]:
import numpy as np
list_var=[1,2,3,4]
print(type(list_var))
print(list_var)

<class 'list'>
[1, 2, 3, 4]


In [7]:
create_array=np.array(list_var)
print(type(create_array))
print(create_array)

<class 'numpy.ndarray'>
[1 2 3 4]


In [8]:
array_2d=np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]
